export const ROUTES = {
    auth: {
        login: '/api/v1/auth/login',
        register: '/api/v1/auth/register',
        logout: '/api/v1/auth/logout',
        refresh: '/api/v1/auth/refresh-token',
        me: '/api/v1/auth/me',
        forgotPassword: '/api/v1/auth/forgot-password',
        resetPassword: '/api/v1/auth/reset-password',
        changePassword: '/api/v1/auth/change-password',
    },
    vehicle: {
        list: '/api/v1/vehicles',
        create: '/api/v1/vehicles',
        update: '/api/v1/vehicles/:id',
        delete: '/api/v1/vehicles/:id',
        details: '/api/v1/vehicles/:id',
        history: '/api/v1/vehicles/:id/history',
        health: '/api/v1/vehicles/:id/health',
        maintenanceSchedule: '/api/v1/vehicles/:id/maintenance-schedule',
    },
    customer: {
        dashboard: '/api/v1/customers/dashboard',
        vehicles: '/api/v1/customers/vehicles',
        appointments: '/api/v1/customers/appointments',
        payments: '/api/v1/customers/payments',
        profile: '/api/v1/customers/profile',
        history: '/api/v1/customers/history',
        notifications: '/api/v1/customers/notifications',
        repairHistory: '/api/v1/customers/repair-history',
    },
    staff: {
        list: '/api/v1/staff',
        dashboard: '/api/v1/staff/dashboard',
        appointments: '/api/v1/staff/appointments',
        profile: '/api/v1/staff/profile',
        workOrders: '/api/v1/staff/work-orders',
    },
    manager: {
        list: '/api/v1/managers',
        dashboard: '/api/v1/manager/dashboard',
        appointments: '/api/v1/manager/appointments',
        staff: '/api/v1/manager/staff',
        createStaff: '/api/v1/staff',
        inventory: '/api/v1/manager/inventory',
        purchaseOrders: '/api/v1/manager/purchase-orders',
        staffManagement: '/api/v1/manager/staff-management',
        reports: '/api/v1/manager/reports',
        profile: '/api/v1/manager/profile',
        customers: '/api/v1/manager/customers',
        vehicles: '/api/v1/manager/vehicles',
    },
} as const;
