export const ROUTES = {
    auth: {
        login: '/auth/login',
        register: '/auth/register',
        logout: '/auth/logout',
        refresh: '/auth/refresh-token',
        me: '/auth/me',
        forgotPassword: '/auth/forgot-password',
        resetPassword: '/auth/reset-password',
        changePassword: '/auth/change-password',
    },
    vehicle: {
        list: '/vehicles',
        create: '/vehicles',
        update: '/vehicles/:id',
        delete: '/vehicles/:id',
        details: '/vehicles/:id',
        history: '/vehicles/:id/history',
        health: '/vehicles/:id/health',
        maintenanceSchedule: '/vehicles/:id/maintenance-schedule',
    },
    customer: {
        dashboard: '/customers/dashboard',
        vehicles: '/customers/vehicles',
        appointments: '/customers/appointments',
        payments: '/customers/payments',
        profile: '/customers/profile',
        history: '/customers/history',
        notifications: '/customers/notifications',
        repairHistory: '/customers/repair-history',
    },
    staff: {
        list: '/staff',
        dashboard: '/staff/dashboard',
        appointments: '/staff/appointments',
        profile: '/staff/profile',
        workOrders: '/staff/work-orders',
    },
    manager: {
        list: '/managers',
        dashboard: '/manager/dashboard',
        appointments: '/manager/appointments',
        staff: '/manager/staff',
        createStaff: '/staff',
        inventory: '/manager/inventory',
        purchaseOrders: '/manager/purchase-orders',
        staffManagement: '/manager/staff-management',
        reports: '/manager/reports',
        profile: '/manager/profile',
        customers: '/manager/customers',
        vehicles: '/manager/vehicles',
    },
} as const;
